import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ReactMarkdown from 'react-markdown'
import Example from './components/Example'

const inter = Inter({ subsets: ['latin'] })

const data = [{title:"Basic", input:"# Hello, *world*!"},
{title:"Math", 
input:"The lift coefficient ($C_L$) is a dimensionless coefficient."},
// {title:"Code", 
// input:"Here is some JavaScript code: ~~~js console.log('It works!')~~~" }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6 max-w-3xl mx-auto">
            <h1 className='text-2xl font-bold text-center mb-6'>MarkDawn</h1>
            {data.map((item,index)=><Example key={index} input={item.input} title={item.title}/>)}

      </main>
    </>
  )
}
